# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hyper_bench_vector <- function(xin, yin, N, n) {
    .Call('_rcellmarker_hyper_bench_vector', PACKAGE = 'rcellmarker', xin, yin, N, n)
}

name_table <- function(lh) {
    .Call('_rcellmarker_name_table', PACKAGE = 'rcellmarker', lh)
}

fast_factor <- function(x) {
    .Call('_rcellmarker_fast_factor', PACKAGE = 'rcellmarker', x)
}

sf <- function(x) {
    .Call('_rcellmarker_sf', PACKAGE = 'rcellmarker', x)
}

uniq <- function(xa) {
    .Call('_rcellmarker_uniq', PACKAGE = 'rcellmarker', xa)
}

